version: 2
jobs:
  build:
    docker:
    - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "lambda-xhr-endpoint/yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: cd lambda-xhr-endpoint && yarn install
      - save_cache:
          paths:
            - lambda-xhr-endpoint/node_modules
          key: v1-dependencies-{{ checksum "lambda-xhr-endpoint/package.json" }}
      - deploy:
          name: "lambda"
          command: make deploylambda
